### PR TITLE
Group Layers by Versions

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview

This PR updates the map to reflect the new changes to the PRN API. The API now returns layers _grouped by "versions",_ with each "version" representing a batch of layers that were uploaded by an admin at one time.

(e.g. when Jim submits a batch of files, via the Upload form, with 1 metadata JSON and 4 layer/heatmap CSV files, those 4 layers will be grouped under "version v1". If he then uploads 1 JSON + 7 CSV files, those 7 layers will be grouped under "version v2". Etc etc)

Previous API response:
```
[
  {
    "name": "overlay_0",
    "url":"https://planetary-response-network.s3.amazonaws.com/events/dominica_2018_demo/layers/pending/v2/overlay_0.csv"
  }
]
```

New (current) API response:
```
[
  {
    "version": "v2",
    "metadata_url": "https://planetary-response-network.s3.amazonaws.com/events/dominica_2018_demo/layers/pending/v2/metadata.json",
    "layers": [
      {
        "name": "overlay_0",
        "url":"https://planetary-response-network.s3.amazonaws.com/events/dominica_2018_demo/layers/pending/v2/overlay_0.csv"
      }
    ]
  }
]
```

### Notes for Testing

To view the map with pending layers: `http://local.zooniverse.org:3735/maps/?event=dominica_2018_demo&pending=1`

To view the map with approved layers: `http://local.zooniverse.org:3735/maps/?event=dominica_2018_demo`

### Status
WIP

Goals:
- [x] Map should now display data from the updated API
- [x] Map should group layers by their version group
- [x] Each Version Group in PENDING MODE should have an "Approve" button

Current Screenshot:
Screen Shot 2019-03-18 at 16 33 33

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Currently available features:
- Map now displays data from the updated API
- Map groups layers by their version group

Screen Shot 2019-03-18 at 16 33 33

**Comment by eatyourgreens** [comment]
Looking at the screenshot, maybe the form design should change so that each layer group is a fieldset?

**Comment by eatyourgreens** [comment]
Looks good to me. Anyone else seeing that the rendering of the map slows down a bit when you have a few layers visible on the screen?

**Comment by shaunanoordin** [comment]
## PR Update

This Version Groups in the Map layers panel now has a link to the Metadata (should the user think it's necessary) and, _if the map is viewing Pending layers,_ those layers now have an Approve button.

Screen Shot 2019-03-18 at 17 11 24

At the moment, I'm getting 404s when _POSTing_ to, e.g. `https://maps-api.planetaryresponsenetwork.org/pending/layers/dominica_2018_demo/approve/v2`, so I'm going to need to follow up on what's going on there.

**Comment by shaunanoordin** [comment]
@eatyourgreens 

- A'doy! You're right, `fieldset` makes more sense than a generic `div` to group the Layers of a Version Group together - I'll make those changes
- I AM getting a significant amount of slowdown when viewing a large number of data points. This happens on two occasions:
  - when changing the selected layers or threshold, there is a noticeable lag before the map re-renders (which, as you pointed out, may be due to the fact that the code parsing through all the datasets before re-rendering)
  - when zooming in/out _(but not panning)_ on a map with a large number of data points (not just a large number of active layers), the zooming action tends to 'stutter' somewhat (transition between zoom levels aren't smooth)

Tested on OSX+Chrome with data sets from the Puerto Rico event (which appears to have more data points than the previous dominica 2018 data). The slowdown issue(s, since there may be two distinct issues here,) may be a concern as we approach larger data sets, but I'm not sure what we can do about it at the moment - especially since the zooming in/out slowdown seems related to the efficiency of the Google Map API itself.

**Pull request merged**
