### PR TITLE
Set map bounds from event metadata

### LINKED ISSUE #23: show all event layers on first load
I've got a few island layers setup but the map zooms in on 1 island instead of showing all layers via an overview. https://prn-maps.planetaryresponsenetwork.org/maps/?pending=true&event=dominica_2018_demo

We can use the event ROI information to derive a source bounding box instead of calculating it from the data layers...
https://maps-api.planetaryresponsenetwork.org/events/dominica_2018_demo
```
{"date":"2019/01/09","name":"Dominca 2018 Demo","bounding_box_coords":[-61.577664,15.185255,-61.143342,15.673547],"geotiff_source_imagery":{"before_image_file_name":"dominica_planet_before.tif","before_image_provider":"dg","after_image_file_name":"dominica_planet_after.tif","after_image_provider":"dg"},"zooniverse_metadata":{"project_id":2419,"subject_set_id":60320},"s3_metadata":{"bucket_name":"planetary-response-network","bucket_path":"dominca_2018","bucket_host_name":"planetary-response-network.s3.amazonaws.com"}}
```

Current behaviour

Screenshot 2019-03-19 at 13 47 14

Closer to desired

Screenshot 2019-03-19 at 13 48 28

### PR DESCRIPTION
**Pull request by eatyourgreens**
Request the event details from the API, then use the event bounding box to set the map bounds.

Closes #23.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This works, but the bounding box in the event metadata doesn't seem to include the points in the map layers.

**Review by shaunanoordin — CHANGES_REQUESTED** [review]
## PR Review
This PR changes the initial map bounds (i.e. where the map is pointing at, and at what zoom level) behaviour.

- Previously, the initial map bounds is determined by calculating the min/average/max of the available data points.
- With this PR, the initial map bounds are spelled out in the PRN Event's metadata. No guessing/calculation is involved - we just pan & zoom to the country that the Event is focused on.

### Issues

Problem: with the current implementation, the Map pans & zooms to the initial map bounds _every time a layer is selected/deselected._

Diagnosis: the cause of this is that the "fit to map bounds" logic is now called at `renderMapAndFit()`, and that function is triggered every time a layer is selected/deselected.

Recommendation: Change `MAP_SELECT.addEventListener('change', renderMapAndFit);` to `MAP_SELECT.addEventListener('change', renderMap);`

### Status

1 change requested

**Comment by shaunanoordin** [comment]
Oh!

> This works, but the bounding box in the event metadata doesn't seem to include the points in the map layers.

If you're using the `dominica_2018_demo` Event, the sample data was uploaded with data points from Puerto Rico and Antigua (the country on the opposite side of Progua) because... uh, because?

The Event metadata for `dominica_2018_demo` correctly focuses on the country the PRN Event is looking for, in this case Dominica, which I guess makes a case for why the metadata coordinates are important.

**Comment by eatyourgreens** [comment]
D'oh! Yes, I originally set this up to pan to any new layer after selecting it.

**Comment by camallen** [comment]
> This works, but the bounding box in the event metadata doesn't seem to include the points in the map layers.

I'll update them now - it's been on my list of stuff todo for a while.

**Comment by eatyourgreens** [comment]
I've changed that event listener. I also moved the main code, which loads in the initial layers, to the bottom of the file, because it was getting lost in the rest of the code.

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

Changes LGTM - this PR is now good to go. 👍 Merging!

**Pull request merged**
